version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - './:/app'
  mongo:
    container_name: mongodb-local
    build:
      context: ./mongo
      dockerfile: Dockerfile
    ports:
      - 27017:27017
    volumes:
      - './mongo/database:/database'
